export const GET_MESSAGE_LIST = 'GET_MESSAGE_LIST'
export const ADD_MESSAGE_LIST_ITEM = 'ADD_MESSAGE_LIST_ITEM'
export const DELETE_MESSAGE_LIST_ITEM = 'DELETE_MESSAGE_LIST_ITEM'
export const SET_MESSAGE_LIST = 'SET_MESSAGE_LIST'

export const SET_CONTEXT = 'SET_CONTEXT';
export const SET_INTENT = 'SET_INTENT';