export const GET_MESSAGE_LIST = 'GET_MESSAGE_LIST'
export const ADD_MESSAGE_LIST_ITEM = 'ADD_MESSAGE_LIST_ITEM'
export const DELETE_MESSAGE_LIST_ITEM = 'DELETE_MESSAGE_LIST_ITEM'
export const SET_MESSAGE_LIST = 'SET_MESSAGE_LIST'

export const SET_CONTEXT = 'SET_CONTEXT';
export const SET_INTENT = 'SET_INTENT';

export const SET_ORIGIN_LOCATION = 'SET_ORIGIN_LOCATION';
export const SET_DESTINATION = 'SET_DESTINATION';

export const SET_IS_JOIN = 'SET_IS_JOIN';

export const SET_EVENT = 'SET_EVENT';